#!/usr/bin/env zsh

fetch_gits() {
  cd $SOUNDBOT && git fetch && git pull
  cd $ANSIBLE_HOME && git fetch && git pull
}

waveform() {
  timestamp=$(date +%s)

  INPUT=$1
  OUTPUT="$TEMP/wavform_$timestamp.png"

  zoom_level = ""
  dimensions = ""
  colors = ""

  cd $PWD

  audiowaveform -i "$INPUT" -o "${OUTPUT}" \
    --pixels-per-second 200 -w 1000 -h 200 \
    --split-channels -c audition --background-color 0f0e0e && \

  feh "$OUTPUT"

}

hamming() {
  timestamp=$(date +%s)

  INPUT=$1
  OUTPUT="$TEMP/hamming_$timestamp.png"
  LABEL="-c hamming -t $2"

  sox -V2 "$INPUT" \
    -n rate 24k spectrogram "$LABEL" \
    -x 800 -z 100 -h -w hamming \
    -o "$OUTPUT"
}

kaiser() {
  timestamp=$(date +%s)

  INPUT=$1
  OUTPUT="$TEMP/kaiser_$timestamp.png"
  LABEL="-c kaiser -t $2"

  sox -V2 "$INPUT" \
    -n rate 24k spectrogram "$LABEL" \
    -x 800 -z 100 -h -w Kaiser \
    -o "$OUTPUT"
}

dolph() {
  timestamp=$(date +%s)

  INPUT=$1
  OUTPUT="$TEMP/dolph_$timestamp.png"
  LABEL="-c dolph -t $2"

  sox -V2 "$INPUT" \
    -n rate 24k spectrogram "$LABEL" \
    -x 800 -z 100 -h -w Dolph \
    -o "$OUTPUT"
}
